splash = false
ipc = false

wallpaper {
    monitor = DP-1
    path = /home/ktz/Pictures/wallpapers/deadlock-drifter.jpg
}
wallpaper {
    monitor = HDMI-A-3
    path = /home/ktz/Pictures/wallpapers/deadlock-drifter.jpg
}
