preload = /home/ktz/Pictures/wallpapers/deadlock-drifter.jpg
wallpaper = DP-1, /home/ktz/Pictures/wallpapers/deadlock-drifter.jpg

preload = /home/ktz/Pictures/wallpapers/deadlock-drifter.jpg
wallpaper = HDMI-A-3, /home/ktz/Pictures/wallpapers/deadlock-drifter.jpg

ipc = true
