# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# windowrule = float,class:^(kitty)$,title:^(kitty)$
windowrule = match:class brave-browser, workspace name:q
windowrule = match:class floorp, workspace name:q
windowrule = match:class steam, workspace name:s
windowrule = match:class net.lutris.Lutris, workspace name:s
windowrule = match:class org.telegram.desktop, workspace name:3
windowrule = match:class signal, workspace name:3
windowrule = match:class vesktop, workspace name:3
windowrule = match:class discord, workspace name:3

# common modals
# windowrule = float,title:^(Open)$
# windowrule = float,title:^(Choose Files)$
# windowrule = float,title:^(Save As)$
# windowrule = float,title:^(Confirm to replace files)$
# windowrule = float,title:^(File Operation Progress)$
# windowrule = float,title:(* wants to save)$
# windowrulev2 = float,class:^(google-chrome)$,title:^(Open Files)$
# windowrulev2 = float,class:^(google-chrome)$,title:^(Open Files)$
# windowrulev2 = float,class:^(brave-browser)$,title:^(Open File)$
# windowrulev2 = float,class:^(brave-browser)$,title:^(Open File)$
# windowrulev2 = float,class:^(xdg-desktop-portal-gtk)$
# windowrule = center,class:org.pulseaudio.pavucontrol
# windowrule = float,class:com.saivert.pwvucontrol

## Picture-in-picture overlays
windowrule {
    name = fix-pip
    match:class = pip
    float = on
    pin = on
    size = 600 338
    keep_aspect_ratio = on
    border_size = 0
    opacity = 1 1
    move = 100%-w-40 4%
}

windowrule {
    name = floats
    match:tag = floating-window
    float = on
    center = on
    size = 800 600
}

windowrule = match:class (blueberry.py|Impala|Wiremix|org.gnome.NautilusPreviewer|com.gabm.satty|Omarchy|About|TUI.float), tag +floating-window
windowrule = match:class (xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus), match:title ^(Open.*Files?|Open Folder|Save.*Files?|Save.*As|Save|All Files), tag +floating-window

# Enable FIFO for games - hyprctl clients
windowrule {
    name = fifo-for-games
    match:title = (VRising|Deadlock|Path of Exile|Path of Exile 2|^(steam_app_.*)|^(bms_linux))
    immediate = on
}

# PoE Stuff
windowrule {
    name=poe
    match:title = (Path of Exile|Path of Exile 2|steam_app_238960)
    tag = +poe
    fullscreen = on
}
windowrule {
    name=apt
    match:title = (Awakened PoE Trade|Exiled Exchange 2)
    float = on
    no_blur = on
    no_focus = on
    no_shadow = on
    border_size = 0
    pin = on
    render_unfocused = on
    size = 100% 100%
    center = on
}
